name: lint
on: [pull_request, push]
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Install module and dependencies
        run: python -m pip install pipx
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      - uses: chartboost/ruff-action@v1
