name: lint
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      - uses: chartboost/ruff-action@v1
